# Generated by Django 3.2.6 on 2021-08-17 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon_evolve_to',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evolution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.evolution')),
                ('id_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pokemons')),
            ],
        ),
    ]
