# Generated by Django 3.2.6 on 2021-08-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evolution_pokemon_evolve_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon_evolve_to',
            old_name='id_evolution',
            new_name='evolution',
        ),
        migrations.RenameField(
            model_name='pokemon_evolve_to',
            old_name='id_pokemon',
            new_name='pokemon',
        ),
        migrations.RenameField(
            model_name='pokemon_has_abilities',
            old_name='id_ability',
            new_name='ability',
        ),
        migrations.RenameField(
            model_name='pokemon_has_abilities',
            old_name='id_pokemon',
            new_name='pokemon',
        ),
    ]
